name: geth
version: 'master'
summary: Official Go implementation of the Ethereum protocol
description: |
    Official Go implementation of the Ethereum protocol
 
grade: stable
confinement: strict

apps:
  abigen:
    command: bin/abigen
  bootnode:
    command: bin/bootnode
    plugs: [network, network-bind]
  evm:
    command: bin/evm
  faucet:
    command: bin/faucet
  geth:
    command: bin/geth
    plugs: [network, network-bind]
  puppeth:
    command: bin/puppeth
    plugs: [network]
  rlpdump:
    command: bin/rlpdump
    plugs: [network]
  swarm:
    command: bin/swarm
    plugs: [network]
  wnode:
    command: bin/wnode
    plugs: [network, network-bind]

parts:
  go17:
    plugin: x-gobuild
    build-packages: [golang-go, rsync]
    source: https://go.googlesource.com/go
    source-type: git
    source-tag: go1.7.5
    prime:
      - -*
  geth:
    after: [go17]
    plugin: go
    source: .
    go-importpath: github.com/ethereum/go-ethereum
